[package]
name = "paqpy"
version = "2.0.0"
authors = ["Gregory Langlais <_@gregorylanglais.com>"]
edition = "2021"
description = "Hash directory or file with BLAKE3."
license = "MIT"
readme = "README.md"
keywords = [
    "hash",
    "blake3",
    "directory-traversal",
    "cryptographic",
    "python",
]
repository = "https://github.com/gregl83/paqpy"
homepage = "https://pypi.org/project/paqpy"
publish = false

[lib]
name = "paqpy"
crate-type = ["cdylib"]

[dependencies]
paq = "~2.0.0"
pyo3 = { version = "0.27.2", features = ["extension-module", "abi3-py37"] }
